[package]
name = "bing_wallpaper"
version = "1.0.0-pre2"
authors = [ "13xforever <ilya.veselov@gmail.com>" ]
edition = "2021"

[dependencies]
rustc-serialize = "0.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }