[package]
name = "bing_wallpaper"
version = "1.0.1"
authors = [ "13xforever <ilya.veselov@gmail.com>" ]

[dependencies]
rustc-serialize = "0.3"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
serde_json = "1.0"